package com.sky.service.impl;
import com.sky.dto.GoodsSalesDTO; import com.sky.entity.Orders; import com.sky.mapper.*; import com.sky.service.*; import com.sky.vo.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Service;
import javax.servlet.http.HttpServletResponse; import java.net.URLEncoder; import java.time.*; import java.util.*; import java.util.stream.Collectors;

/** 统计报表业务，序列字符串供前端 ECharts 使用。 */
@Service
public class ReportServiceImpl implements ReportService {
 @Autowired private OrderMapper orderMapper; @Autowired private UserMapper userMapper; @Autowired private WorkspaceService workspace;
 private List<LocalDate> dates(LocalDate b,LocalDate e){List<LocalDate> r=new ArrayList<>(); for(LocalDate d=b;!d.isAfter(e);d=d.plusDays(1))r.add(d); return r;}
 private String join(Collection<?> c){return c.stream().map(String::valueOf).collect(Collectors.joining(","));}
 private Map<String,Object> range(LocalDate d){Map<String,Object> m=new HashMap<>();m.put("begin",d.atStartOfDay());m.put("end",d.atTime(LocalTime.MAX));return m;}
 public TurnoverReportVO turnover(LocalDate b,LocalDate e){List<LocalDate> ds=dates(b,e);List<Double> values=new ArrayList<>();for(LocalDate d:ds){Map<String,Object>m=range(d);m.put("status",Orders.COMPLETED);Double v=orderMapper.sumByMap(m);values.add(v==null?0D:v);}return TurnoverReportVO.builder().dateList(join(ds)).turnoverList(join(values)).build();}
 public UserReportVO users(LocalDate b,LocalDate e){List<LocalDate>ds=dates(b,e);List<Integer> total=new ArrayList<>(),added=new ArrayList<>();for(LocalDate d:ds){Map<String,Object>m=range(d);added.add(userMapper.countByMap(m));m.remove("begin");total.add(userMapper.countByMap(m));}return UserReportVO.builder().dateList(join(ds)).totalUserList(join(total)).newUserList(join(added)).build();}
 public OrderReportVO orders(LocalDate b,LocalDate e){List<LocalDate>ds=dates(b,e);List<Integer> all=new ArrayList<>(),valid=new ArrayList<>();for(LocalDate d:ds){Map<String,Object>m=range(d);all.add(orderMapper.countByMap(m));m.put("status",Orders.COMPLETED);valid.add(orderMapper.countByMap(m));}int ta=all.stream().mapToInt(i->i).sum(),tv=valid.stream().mapToInt(i->i).sum();return OrderReportVO.builder().dateList(join(ds)).orderCountList(join(all)).validOrderCountList(join(valid)).totalOrderCount(ta).validOrderCount(tv).orderCompletionRate(ta==0?0D:(double)tv/ta).build();}
 public SalesTop10ReportVO top10(LocalDate b,LocalDate e){List<GoodsSalesDTO> l=orderMapper.getSalesTop10(b.atStartOfDay(),e.atTime(LocalTime.MAX));return SalesTop10ReportVO.builder().nameList(join(l.stream().map(GoodsSalesDTO::getName).collect(Collectors.toList()))).numberList(join(l.stream().map(GoodsSalesDTO::getNumber).collect(Collectors.toList()))).build();}
 public void export(HttpServletResponse response){LocalDate end=LocalDate.now().minusDays(1),begin=end.minusDays(29);try(XSSFWorkbook wb=new XSSFWorkbook()){org.apache.poi.ss.usermodel.Sheet s=wb.createSheet("运营数据");String[] h={"日期","营业额","有效订单","完成率","平均客单价","新增用户"};org.apache.poi.ss.usermodel.Row hr=s.createRow(0);for(int i=0;i<h.length;i++)hr.createCell(i).setCellValue(h[i]);int row=1;for(LocalDate d:dates(begin,end)){BusinessDataVO v=workspace.getBusinessData(d.atStartOfDay(),d.atTime(LocalTime.MAX));org.apache.poi.ss.usermodel.Row r=s.createRow(row++);r.createCell(0).setCellValue(d.toString());r.createCell(1).setCellValue(v.getTurnover());r.createCell(2).setCellValue(v.getValidOrderCount());r.createCell(3).setCellValue(v.getOrderCompletionRate());r.createCell(4).setCellValue(v.getUnitPrice());r.createCell(5).setCellValue(v.getNewUsers());}for(int i=0;i<h.length;i++)s.autoSizeColumn(i);response.setContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");response.setHeader("Content-Disposition","attachment;filename="+URLEncoder.encode("运营数据报表.xlsx","UTF-8"));wb.write(response.getOutputStream());}catch(Exception e){throw new RuntimeException("导出报表失败",e);}}
}
